version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moba-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: moba_test
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: moba-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data:
