spring:
  config:
    import:
      #      - classpath:application-auth.yml
      - classpath:application-redis.yml
      - classpath:application-mail.yml
      - classpath:application-jwt.yml
      - classpath:application-mysql.yml
      - classpath:application-kakao.yml
      - classpath:application-s3.yml
      - classpath:application-cors.yml
      - classpath:application-wallet.yml
      #      - classpath:application-firebase.yml
      #      - classpath:application-mongo.yml
      #      - classpath:application-elastic.yml
      - optional:file:.env[.properties]
  application:
    name: moba
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  web:
    resources:
      add-mappings: false

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
